const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));

const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.1,rootMargin:'0px 0px -30px'});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const checks=[...document.querySelectorAll('.console-check')];const percent=document.getElementById('meter-percent');const bar=document.getElementById('meter-bar');const states=[[1,72],[2,84],[3,93],[4,100]];let stateIndex=0;
function updateScreeningDemo(){if(!checks.length||!percent||!bar)return;const[completedCount,progress]=states[stateIndex];checks.forEach((row,index)=>{const icon=row.querySelector('.check-icon');const status=row.querySelector('em');row.classList.remove('complete','running','queued');if(index<completedCount){row.classList.add('complete');if(icon)icon.textContent='✓';if(status)status.textContent='Complete'}else if(index===completedCount&&completedCount<checks.length){row.classList.add('running');if(icon)icon.textContent='⌕';if(status)status.textContent='Running'}else{row.classList.add('queued');if(icon)icon.textContent='+';if(status)status.textContent='Queued'}});percent.textContent=`${progress}%`;bar.style.width=`${progress}%`;stateIndex=(stateIndex+1)%states.length}
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)setInterval(updateScreeningDemo,2600);

document.querySelectorAll('.faq-list details').forEach(item=>item.addEventListener('toggle',()=>{if(!item.open)return;document.querySelectorAll('.faq-list details').forEach(other=>{if(other!==item)other.open=false})}));

const contactForm=document.getElementById('contact-form');
const contactStatus=document.getElementById('form-status');
const interestSelect=document.getElementById('contact-interest');
if(interestSelect){const requestedInterest=new URLSearchParams(window.location.search).get('interest');if(requestedInterest&&[...interestSelect.options].some(option=>option.value===requestedInterest))interestSelect.value=requestedInterest;}
if(contactForm){contactForm.addEventListener('submit',async event=>{event.preventDefault();const submitButton=contactForm.querySelector('button[type="submit"]');const originalText=submitButton?.innerHTML;if(submitButton){submitButton.disabled=true;submitButton.innerHTML='Sending…';}if(contactStatus){contactStatus.className='form-status';contactStatus.textContent='';}try{const response=await fetch(contactForm.action,{method:'POST',body:new FormData(contactForm),headers:{Accept:'application/json'}});if(response.ok){contactForm.reset();if(contactStatus){contactStatus.className='form-status success';contactStatus.textContent='Thank you. Your information was sent to Brango Connect and our team will follow up with you.';}}else{throw new Error('Form submission failed');}}catch(error){if(contactStatus){contactStatus.className='form-status error';contactStatus.innerHTML='We could not send the form. Please try again or email <a href="mailto:info@brangoconnect.com">info@brangoconnect.com</a>.';}}finally{if(submitButton){submitButton.disabled=false;submitButton.innerHTML=originalText;}}});}
